package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	commonv1 "gql-template/gen/grpc/common/v1"
	examplev1 "gql-template/gen/grpc/example/v1"
	"gql-template/graph/model"

	"github.com/kitti12911/lib-util/ptr"
)

// CreateExample is the resolver for the createExample field.
func (r *mutationResolver) CreateExample(ctx context.Context, input model.CreateExampleInput) (*model.CreateExampleResult, error) {
	resp, err := r.ExampleClient.CreateExample(ctx, &examplev1.CreateExampleRequest{
		Example: &examplev1.Example{
			Name:        input.Name,
			Description: input.Description,
		},
	})
	if err != nil {
		return nil, err
	}

	return &model.CreateExampleResult{
		ID: resp.GetId(),
	}, nil
}

// UpdateExample is the resolver for the updateExample field.
func (r *mutationResolver) UpdateExample(ctx context.Context, id string, input model.UpdateExampleInput) (*model.UpdateExampleResult, error) {
	resp, err := r.ExampleClient.UpdateExample(ctx, &examplev1.UpdateExampleRequest{
		Id: id,
		Example: &examplev1.Example{
			Name:        input.Name,
			Description: input.Description,
			Status:      input.Status,
		},
	})
	if err != nil {
		return nil, err
	}

	return &model.UpdateExampleResult{
		AffectedRows: int(resp.GetAffectedRows()),
	}, nil
}

// UpdateExamplePartial is the resolver for the updateExamplePartial field.
func (r *mutationResolver) UpdateExamplePartial(ctx context.Context, id string, input model.UpdateExamplePartialInput) (*model.UpdateExamplePartialResult, error) {
	example := &examplev1.Example{}
	mask := model.ApplyUpdateExamplePartialInput(input, example)

	resp, err := r.ExampleClient.UpdateExamplePartial(ctx, &examplev1.UpdateExamplePartialRequest{
		Id:         id,
		Example:    example,
		UpdateMask: mask,
	})
	if err != nil {
		return nil, err
	}

	return &model.UpdateExamplePartialResult{
		AffectedRows: int(resp.GetAffectedRows()),
	}, nil
}

// DeleteExample is the resolver for the deleteExample field.
func (r *mutationResolver) DeleteExample(ctx context.Context, id string) (*model.DeleteExampleResult, error) {
	resp, err := r.ExampleClient.DeleteExample(ctx, &examplev1.DeleteExampleRequest{
		Id: id,
	})
	if err != nil {
		return nil, err
	}

	return &model.DeleteExampleResult{
		AffectedRows: int(resp.GetAffectedRows()),
	}, nil
}

// Example is the resolver for the example field.
func (r *queryResolver) Example(ctx context.Context, id string) (*model.Example, error) {
	resp, err := r.ExampleClient.GetExample(ctx, &examplev1.GetExampleRequest{
		Id: id,
	})
	if err != nil {
		return nil, err
	}

	e := resp.GetExample()
	return &model.Example{
		ID:          e.GetId(),
		Name:        e.GetName(),
		Description: e.GetDescription(),
		Status:      e.GetStatus(),
		CreatedAt:   e.GetCreatedAt().AsTime(),
		UpdatedAt:   e.GetUpdatedAt().AsTime(),
	}, nil
}

// Examples is the resolver for the examples field.
func (r *queryResolver) Examples(ctx context.Context, page *int, pageSize *int, filter *string, orderBy *string) (*model.ExampleList, error) {
	req := &examplev1.ListExamplesRequest{
		Pagination: &commonv1.PaginationRequest{
			Page:     int32(ptr.From(page)),
			PageSize: int32(ptr.From(pageSize)),
		},
		Filter:  ptr.From(filter),
		OrderBy: ptr.From(orderBy),
	}

	resp, err := r.ExampleClient.ListExamples(ctx, req)
	if err != nil {
		return nil, err
	}

	examples := make([]*model.Example, len(resp.GetExamples()))
	for i, e := range resp.GetExamples() {
		examples[i] = &model.Example{
			ID:          e.GetId(),
			Name:        e.GetName(),
			Description: e.GetDescription(),
			Status:      e.GetStatus(),
			CreatedAt:   e.GetCreatedAt().AsTime(),
			UpdatedAt:   e.GetUpdatedAt().AsTime(),
		}
	}

	pag := resp.GetPagination()
	return &model.ExampleList{
		Examples:   examples,
		Page:       int(pag.GetPage()),
		PageSize:   int(pag.GetPageSize()),
		TotalPages: int(pag.GetTotalPages()),
		TotalSize:  int(pag.GetTotalSize()),
	}, nil
}
