// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateExampleInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type CreateExampleResult struct {
	ID string `json:"id"`
}

type DeleteExampleResult struct {
	AffectedRows int `json:"affectedRows"`
}

type Example struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type ExampleList struct {
	Examples   []*Example `json:"examples"`
	Page       int        `json:"page"`
	PageSize   int        `json:"pageSize"`
	TotalPages int        `json:"totalPages"`
	TotalSize  int        `json:"totalSize"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateExampleInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Status      string `json:"status"`
}

type UpdateExamplePartialResult struct {
	AffectedRows int `json:"affectedRows"`
}

type UpdateExampleResult struct {
	AffectedRows int `json:"affectedRows"`
}
