// Code generated by gen-nullable; DO NOT EDIT.

package model

import (
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/known/fieldmaskpb"
)

type UpdateExamplePartialInput struct {
	Name        NullableString `json:"name"`
	Description NullableString `json:"description"`
	Status      NullableString `json:"status"`
}

func ApplyUpdateExamplePartialInput(input UpdateExamplePartialInput, msg proto.Message) *fieldmaskpb.FieldMask {
	var paths []string
	msgReflect := msg.ProtoReflect()

	if input.Name.Set {
		if input.Name.Value != nil {
			if fd := msgReflect.Descriptor().Fields().ByName("name"); fd != nil {
				msgReflect.Set(fd, protoreflect.ValueOfString(*input.Name.Value))
			}
		}
		paths = append(paths, "name")
	}

	if input.Description.Set {
		if input.Description.Value != nil {
			if fd := msgReflect.Descriptor().Fields().ByName("description"); fd != nil {
				msgReflect.Set(fd, protoreflect.ValueOfString(*input.Description.Value))
			}
		}
		paths = append(paths, "description")
	}

	if input.Status.Set {
		if input.Status.Value != nil {
			if fd := msgReflect.Descriptor().Fields().ByName("status"); fd != nil {
				msgReflect.Set(fd, protoreflect.ValueOfString(*input.Status.Value))
			}
		}
		paths = append(paths, "status")
	}

	return &fieldmaskpb.FieldMask{Paths: paths}
}
